name: CI Pipeline

on:
  pull_request:
    branches:
      - '*'  # Dit zorgt ervoor dat de pipeline draait bij elk pull request naar een branch
  schedule:
    - cron: '0 0 * * 0'  # Deze cron job zorgt ervoor dat de pipeline elke zondag om middernacht draait.

jobs:
  build:
    runs-on: ubuntu-latest  # Dit betekent dat de pipeline draait op een Ubuntu-machine

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3  # Haalt de code uit je repository

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12 # Zet Python op de juiste versie

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --use-deprecated=legacy-resolver -r requirements.txt
    - name: Install Pytest
      run: pip install pytest  # Install pytest
    - name: Run Pytest
      run: |
        pytest hello.py

    - name: Run Bandit (SAST) - Security Analysis
      run: |
        pip install bandit
        bandit -r . -v
      continue-on-error: false  # Fail the PR if issues are found

    - name: Run Dependency Vulnerability Check (Safety)
      run: |
        pip install safety
        safety check --full-report
      continue-on-error: false  # Fail the PR if vulnerable dependencies are found

    - name: Run Gitleaks (Secrets Scan)
      uses: gitleaks/gitleaks-action@v1
      with:
        config-path: .gitleaks.toml  # Optional: If you have custom config, provide it here
      continue-on-error: false  # Fail the PR if secrets are found

    - name: Success
      run: echo "All checks passed successfully!"
      if: success()  # This step only runs if all checks pass # Dit zorgt ervoor dat dit bericht alleen verschijnt als alle checks geslaagd zijn
